# build from an image with cabal dependencies installed (saves time)
FROM avus:dev

WORKDIR /opt/avus

# update src and test, run tests
ADD avus.cabal /opt/avus/
ADD src /opt/avus/src
ADD test /opt/avus/test
ADD examples /opt/avus/examples
RUN cabal test
RUN cabal build && cabal install

WORKDIR /opt/avus/examples
RUN avus "sample.csv" --dyre-debug
